ARG BASE_IMAGE=rust:1.43-alpine
FROM ${BASE_IMAGE} AS builder
LABEL mantainer pando855@gmail.com

WORKDIR /usr/src/rash
COPY . .
RUN apk add --no-cache build-base && \
    # muslc does not support dynamic linking:
    # https://github.com/rust-lang/rust/issues/34987
    RUSTFLAGS="-C target-feature=-crt-static" cargo build --release

FROM alpine:3.11
LABEL mantainer pando855@gmail.com

COPY --from=builder /usr/src/rash/target/release/rash /bin/rash
CMD ["/bin/rash"]

