ARG BASE_IMAGE=ekidd/rust-musl-builder:1.44.0
FROM ${BASE_IMAGE} AS builder
LABEL mantainer pando855@gmail.com

ADD --chown=rust:rust . ./
RUN rustup target add armv7-unknown-linux-musleabihf
RUN cargo build --target=armv7-unknown-linux-musleabihf --release

FROM scratch
LABEL mantainer pando855@gmail.com

COPY --from=builder \
    /home/rust/src/target/armv7-unknown-linux-musleabihf/release/rash \
    /bin/
ENTRYPOINT [ "/bin/rash" ]

