#!/bin/sh

set -e

echo '+cargo clippy --locked --all-targets --all-features -- -D warnings'
cargo clippy --locked --all-targets --all-features -- -D warnings
echo '+cargo fmt -- --check'
cargo fmt -- --check
